### ISSUE TITLE
Error from MCMMO (parties)

### ISSUE THREAD

**Issue by Ekkoy06** [ChanceSD/PvPManager#483]
Hi, i got this error, is something about party system from mcmmo

```[00:10:19 INFO]: [PvPManager] mcMMO Found! Hooked successfully
[00:10:19 WARN]: [PvPManager] Failed to enable support for mcMMO v2.2.006. Is mcMMO up to date?
[00:10:19 WARN]: java.lang.NullPointerException: Cannot invoke "com.gmail.nossr50.party.PartyManager.getParties()" because the return value of "com.gmail.nossr50.mcMMO.getPartyManager()" is null
[00:10:19 WARN]:        at mcMMO.jar//com.gmail.nossr50.api.PartyAPI.getParties(PartyAPI.java:83)
[00:10:19 WARN]:        at PvPManager-3.31.1.jar//nc.eA.<init>(SourceFile:16)
[00:10:19 WARN]:        at PvPManager-3.31.1.jar//nc.fA.<init>(SourceFile:4156)
[00:10:19 WARN]:        at PvPManager-3.31.1.jar//me.NoChance.PvPManager.PvPManager.onEnable(SourceFile:80)
[00:10:19 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[00:10:19 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188)
[00:10:19 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[00:10:19 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[00:10:19 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639)
[00:10:19 WARN]:        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550)
[00:10:19 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671)
[00:10:19 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
[00:10:19 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:309)
[00:10:19 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1131)
[00:10:19 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[00:10:19 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by ChanceSD** [comment]
You can ignore that error if the plugin still starts properly but will be fixed.
Do you have parties disabled in mcMMO?

**Comment by Ekkoy06** [comment]
yep, for the moment we have parties disabled (in past happend to enter in pvp mode when players were in the same party)

**Comment by ChanceSD** [comment]
Alright, thanks for the report, should be fixed in the next update.
